### PR TITLE
[Installation] Support integrating using CocoaPods

### LINKED ISSUE #6: Publish to CocoaPods?
It seems the repo already have the latest podspec, any reason it is not on cocoapods yet?

### PR DESCRIPTION
**Pull request by iwasrobbed-ks**
Fixes #6

### ~~Open~~ Closed Question(s)

- Should the iOS target really set the preprocessor flag `OS_MACOSX=1` like you have in the original project? We aren't currently doing this and it seems to work fine on iOS.
  - Yes, see [rocksdb build scripts](https://github.com/facebook/rocksdb/blob/c465509379d72068c19b55dbc69bf08d8c387fbe/build_tools/build_detect_platform#L136)

### Review Steps

Sanity check everything and feel free to improve upon any script details since I'm not great in that area.

Assuming travisCI doesn't timeout, a passing build means everything is working as it should. (We ask travis to specifically wait 30 minutes before timing out on the pod lint task just in case)

### Integration Tests

See the iOS and macOS example apps that both build properly here: https://github.com/rob-keepsafe/rocksdb_example

### Core Changes

- Updates `ObjectiveRocks.podspec` to match the original project settings
  - This includes ensuring header access is scoped properly
- Introduces a shell script `clean_rocksdb_source.sh` which is run after a pod is downloaded to generate a "cleaned" (e.g. relevant source files only) version of the `rocksdb` directory
  - Since many projects check in the `Pods/` directory that gets generated when they install their pods, this saves on including a lot of extraneous files in their app repo
  - As a bonus, this script will also be useful to check diffs between rocksdb releases to see if any ObjectiveRocks code needs updating
- Adds a guard in `.travis.yml` for any breaking changes (this will increase build times a bit)

### Linting Steps

Note: this script will delete the submodule as part of its "clean up" but this will realistically only happen once people install this pod.

1. Check out my forked branch
2. Run `$ pod lib lint --skip-import-validation --no-clean --verbose --allow-warnings`
3. Ensure everything validates well (it'll do both iOS and macOS in one shot)
4. Run `$ git submodule update --init` to reset the repo back
5. Delete the `rocksdb_src` directory it generated

Then once you're ready and you have a `0.8.0` tag updated to the latest commit (after merging this PR) you can push the spec to the CocoaPods master repo using `$ pod trunk push --skip-import-validation --allow-warnings`

### Additional Changes

- Fixes a compilation error in `RocksDBBackupEngine.mm` on macOS target (this happens in your project as well)
- Bumps project settings to Xcode 9.3

### CODE REVIEW

**Comment by iabudiab** [comment]
@rob-keepsafe 

Thanks a ton for this!

### Open Questions

> Should the iOS target really set the preprocessor flag OS_MACOSX=1 like you have in the original project? We aren't currently doing this and it seems to work fine on iOS.

The flas `OS_MACOSX` may indeed not be needed for iOS. I haven't really verified this nor did come up with them myself. I've just copied them from the build scripts of `rocksdb` itself. Take a look at:
 [https://github.com/facebook/rocksdb/blob/c465509379d72068c19b55dbc69bf08d8c387fbe/build_tools/build_detect_platform#L136](https://github.com/facebook/rocksdb/blob/c465509379d72068c19b55dbc69bf08d8c387fbe/build_tools/build_detect_platform#L136)

### Podspec

Is there a reason for `sst_dump_tool` to be treated differently from the other `rocksdb/tools/**`?

**Comment by iwasrobbed-ks** [comment]
Glad to help out and try to repay all the work you've done in some small way!

Ah, good call I hadn't checked the rocksdb build scripts! I'll leave that flag in then and make sure we include it as well.

Re: `sst_dump_tool` handling: I initially deleted all of the `tools` directory, but then it complained about importing `sst_dump_tool_imp.h` in `db_impl` so I put it back in.

**Comment by iabudiab** [comment]
@rob-keepsafe 👍 

I'll fix some warnings and push them onto this PR and then merge it. 

Thanks again!!!

**Comment by iwasrobbed-ks** [comment]
Awesome, thanks so much @iabudiab !!

**Pull request merged**
